language: python
python:
  - "3.5"
addons:
  sonarcloud:
    organisation: "ouisouss-github"
install:
  - pip install -r project/requirements.txt
script:
  - cd project/
  - sonar-scanner -X
  - echo "Starting test..."
  - nosetests tests/*