branches:
  only:
  - master
  - integrate_exabgp
language: python
python:
  - "3.5"
addons:
  sonarcloud:
    organisation: "ouisouss-github"
install:
  - pip install -r project/requirements.txt
script:
  - nosetests project/backend/tests/*
  - cd project
  - nosetests --with-xunit --with-coverage --cover-package=backend --cover-inclusive --cover-xml backend/tests/*
  - (cd backend; ./run.sh &)
  - (cd frontend; ./run_tests.sh)
  - cd ..
  - bash generate-pylint-report.sh
  - sonar-scanner