branches:
  only:
  - master
  - development
language: python
python:
  - "3.5"
addons:
  sonarcloud:
    organisation: "ouisouss-github"
install:
  - pip install -r project/requirements.txt
script:
  - echo "Starting test..."
  - nosetests project/backend/tests/*
  - echo "Starting cover test..."
  - cd project
  - nosetests --with-xunit --with-coverage --cover-package=backend --cover-inclusive --cover-xml backend/tests/unittest_base.py
  - cd ..
  - sonar-scanner